// File originally generated by FlutterFire CLI; values updated by hand
// to point at the legacy Unity Firebase project (`vozhaomuzz`) which
// is the one actively used by the existing user base + push pipeline.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'add this platform to the Firebase console.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'add this platform to the Firebase console.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'add this platform to the Firebase console.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web is not used yet — values are placeholders so kIsWeb branch
  /// doesn't crash if a developer runs the app in a browser.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumIydOJ3BJv5fw3k032ijOQucVsDGeF0',
    appId: '1:521063033191:android:31cd30f20bd42e906427c2',
    messagingSenderId: '521063033191',
    projectId: 'vozhaomuzz',
    storageBucket: 'vozhaomuzz.firebasestorage.app',
  );

  /// iOS — `com.donishsoft.vozhaomuz1`.
  /// Mirrors `ios/Runner/GoogleService-Info.plist`.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhIS7GWRY46KhkzrxviEqnPmRMwSroSbA',
    appId: '1:521063033191:ios:a050b5103dd8de506427c2',
    messagingSenderId: '521063033191',
    projectId: 'vozhaomuzz',
    storageBucket: 'vozhaomuzz.firebasestorage.app',
    iosBundleId: 'com.donishsoft.vozhaomuz1',
  );

  /// Android — `com.vozhaomuz`.
  /// Mirrors `android/app/google-services.json`.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumIydOJ3BJv5fw3k032ijOQucVsDGeF0',
    appId: '1:521063033191:android:31cd30f20bd42e906427c2',
    messagingSenderId: '521063033191',
    projectId: 'vozhaomuzz',
    storageBucket: 'vozhaomuzz.firebasestorage.app',
  );
}
