// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuY6aP-rOK-odu8xWI8V46g3rTW1_YDmk',
    appId: '1:444193525842:web:077a20f213baefb9ee4f8b',
    messagingSenderId: '444193525842',
    projectId: 'vozhaomuz-e48af',
    authDomain: 'vozhaomuz-e48af.firebaseapp.com',
    storageBucket: 'vozhaomuz-e48af.firebasestorage.app',
    measurementId: 'G-JF8DG2X9Q6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4CUAJL5_-EuJCVVAIdolQjbOwmrozMlE',
    appId: '1:444193525842:ios:6e2ced9145f414edee4f8b',
    messagingSenderId: '444193525842',
    projectId: 'vozhaomuz-e48af',
    storageBucket: 'vozhaomuz-e48af.firebasestorage.app',
    iosBundleId: 'com.donishsoft.vozhaomuz1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI3RuDrK72FOTr9wLLFpl4ZijITPpmj8E',
    appId: '1:444193525842:android:aad79b8a11f1db01ee4f8b',
    messagingSenderId: '444193525842',
    projectId: 'vozhaomuz-e48af',
    storageBucket: 'vozhaomuz-e48af.firebasestorage.app',
  );

}